/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#fbf2ed",
        "primary-fixed-dim": "#aacfbb",
        "secondary-fixed": "#ffdea7",
        "surface-container-high": "#efe6e2",
        "outline-variant": "#c1c8c2",
        "surface-dim": "#e1d8d4",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#271900",
        "on-secondary-fixed-variant": "#5e4200",
        "on-tertiary-fixed-variant": "#474743",
        background: "#fff8f5",
        "surface-bright": "#fff8f5",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#373733",
        secondary: "#7c5800",
        "on-primary-container": "#84a895",
        "on-primary-fixed": "#002115",
        "primary-fixed": "#c5ebd7",
        "on-secondary-container": "#745200",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "primary-container": "#1b3d2f",
        "surface-tint": "#436556",
        "on-tertiary-fixed": "#1c1c18",
        outline: "#727974",
        "inverse-primary": "#aacfbb",
        "on-primary": "#ffffff",
        "secondary-container": "#fdc65c",
        "surface-container-highest": "#e9e1dc",
        "surface-container": "#f5ece7",
        "on-primary-fixed-variant": "#2c4d3f",
        "surface-container-lowest": "#ffffff",
        tertiary: "#22221e",
        "on-surface": "#1e1b18",
        "on-background": "#1e1b18",
        "inverse-surface": "#34302c",
        "on-surface-variant": "#414844",
        surface: "#fff8f5",
        "inverse-on-surface": "#f8efea",
        "secondary-fixed-dim": "#f4be55",
        "surface-variant": "#e9e1dc",
        "on-tertiary-container": "#a1a09b",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e5e2dc",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c9c6c1",
        primary: "#03271a",
      },
      fontFamily: {
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        "container-max": "1200px",
        md: "24px",
        sm: "12px",
        unit: "8px",
        xs: "4px",
        lg: "48px",
        gutter: "24px",
      },
      animation: {
        "spin-slow": "spin 20s linear infinite",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
