# -*- coding: utf-8 -*-
"""code_nakshatra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgbhDE0qB5rbOjco845li2FalXfSyoAw
"""

pip install pandas numpy faker scikit-learn

# =========================================================
# AIDCHAIN — REALISTIC NGO FRAUD DATASET GENERATOR
# =========================================================

import pandas as pd
import numpy as np
import random

from faker import Faker
from uuid import uuid4
from datetime import datetime, timedelta

fake = Faker()

np.random.seed(42)
random.seed(42)

NUM_ROWS = 12000

# =========================================================
# NGO PROFILES
# =========================================================

NGO_PROFILES = []

for _ in range(150):

    trust_score = np.random.normal(65, 18)

    trust_score = np.clip(
        trust_score,
        5,
        98
    )

    approval_rate = np.random.normal(
        0.75,
        0.18
    )

    approval_rate = np.clip(
        approval_rate,
        0.10,
        0.99
    )

    NGO_PROFILES.append({

        "ngo_id": str(uuid4()),

        "ngo_name": fake.company(),

        "trust_score": round(trust_score, 2),

        "historical_approval_rate": round(
            approval_rate,
            2
        ),

        "avg_claim_amount": random.randint(
            1500,
            10000
        )
    })

# =========================================================
# DATASET
# =========================================================

dataset = []

for _ in range(NUM_ROWS):

    ngo = random.choice(NGO_PROFILES)

    # -----------------------------------------------------
    # NORMAL DISTRIBUTIONS
    # -----------------------------------------------------

    ocr_amount = max(
        100,
        int(np.random.normal(5000, 2500))
    )

    # MOST claims are near OCR amount
    claimed_amount = int(

        ocr_amount

        * np.random.normal(
            1.08,
            0.45
        )
    )

    claimed_amount = max(
        100,
        claimed_amount
    )

    # -----------------------------------------------------
    # GEO
    # -----------------------------------------------------

    location_distance_km = abs(
        np.random.normal(20, 18)
    )

    # -----------------------------------------------------
    # FREQUENCY
    # -----------------------------------------------------

    submission_frequency = max(
        1,
        int(np.random.normal(5, 4))
    )

    # -----------------------------------------------------
    # TIME
    # -----------------------------------------------------

    submission_hour = random.randint(0, 23)

    # -----------------------------------------------------
    # NGO HISTORY
    # -----------------------------------------------------

    trust_score = ngo["trust_score"]

    historical_approval_rate = ngo[
        "historical_approval_rate"
    ]

    avg_claim_amount = ngo[
        "avg_claim_amount"
    ]

    # =====================================================
    # FRAUD PROBABILITY ENGINE
    # =====================================================

    fraud_probability = 0.03

    # -----------------------------------------------------
    # FINANCIAL SIGNALS
    # -----------------------------------------------------

    amount_difference = abs(
        claimed_amount - ocr_amount
    )

    amount_ratio = (
        claimed_amount / ocr_amount
    )

    if amount_difference > 2500:
        fraud_probability += 0.10

    if amount_difference > 5000:
        fraud_probability += 0.15

    if amount_ratio > 2.0:
        fraud_probability += 0.10

    # -----------------------------------------------------
    # GEO SIGNALS
    # -----------------------------------------------------

    if location_distance_km > 40:
        fraud_probability += 0.10

    if location_distance_km > 80:
        fraud_probability += 0.15

    # -----------------------------------------------------
    # NGO HISTORY SIGNALS
    # -----------------------------------------------------

    if trust_score < 40:
        fraud_probability += 0.12

    if historical_approval_rate < 0.50:
        fraud_probability += 0.12

    # -----------------------------------------------------
    # SPAM SIGNALS
    # -----------------------------------------------------

    if submission_frequency > 10:
        fraud_probability += 0.08

    if submission_frequency > 15:
        fraud_probability += 0.10

    # -----------------------------------------------------
    # TIME SIGNALS
    # -----------------------------------------------------

    if submission_hour <= 4:
        fraud_probability += 0.05

    # -----------------------------------------------------
    # RANDOM NOISE
    # VERY IMPORTANT
    # -----------------------------------------------------

    fraud_probability += np.random.normal(
        0,
        0.08
    )

    fraud_probability = np.clip(
        fraud_probability,
        0.01,
        0.95
    )

    # =====================================================
    # FINAL FRAUD LABEL
    # =====================================================

    is_fraud = np.random.choice(

        [0, 1],

        p=[
            1 - fraud_probability,
            fraud_probability
        ]
    )

    # =====================================================
    # TIMESTAMP
    # =====================================================

    submission_time = (
        datetime.now()
        - timedelta(
            days=random.randint(0, 90)
        )
    )

    # =====================================================
    # FEATURE BASE
    # =====================================================

    amount_difference = abs(
        claimed_amount - ocr_amount
    )

    amount_ratio = round(
        claimed_amount / ocr_amount,
        2
    )

    # =====================================================
    # RECORD
    # =====================================================

    row = {

        "submission_id": str(uuid4()),

        "ngo_id": ngo["ngo_id"],

        "ngo_name": ngo["ngo_name"],

        # Financial
        "ocr_amount": ocr_amount,
        "claimed_amount": claimed_amount,
        "avg_claim_amount": avg_claim_amount,

        "amount_difference": amount_difference,

        "amount_ratio": amount_ratio,

        # NGO
        "trust_score": trust_score,

        "historical_approval_rate":
            historical_approval_rate,

        # Geo
        "location_distance_km":
            round(location_distance_km, 2),

        # Behavior
        "submission_frequency":
            submission_frequency,

        # Time
        "submission_hour":
            submission_hour,

        "submission_timestamp":
            submission_time,

        # Target
        "is_fraud":
            is_fraud
    }

    dataset.append(row)

# =========================================================
# CREATE DATAFRAME
# =========================================================

df = pd.DataFrame(dataset)

# =========================================================
# SAVE
# =========================================================

df.to_csv(
    "synthetic_ngo_fraud_dataset.csv",
    index=False
)

# =========================================================
# SUMMARY
# =========================================================

print("\n=================================================")
print("REALISTIC DATASET GENERATED")
print("=================================================\n")

print("Dataset Shape:", df.shape)

print("\nFraud Distribution:\n")
print(df["is_fraud"].value_counts())

print("\nFraud Percentage:\n")

print(
    df["is_fraud"].value_counts(normalize=True)
)

print("\nSample Rows:\n")

print(df.head())

!pip install pandas numpy matplotlib scikit-learn seaborn faker

import pandas as pd

# Load dataset

df = pd.read_csv("synthetic_ngo_fraud_dataset.csv")

# First 5 rows
print(df.head())

print("Dataset Shape:", df.shape)

print(df.columns)

print(df.dtypes)

print(df.isnull().sum())

print("Duplicate Rows:", df.duplicated().sum())

# Remove duplicate rows

df = df.drop_duplicates()

# Convert timestamp column

df['submission_timestamp'] = pd.to_datetime(
    df['submission_timestamp']
)

print(df.shape)

import matplotlib.pyplot as plt

#graph distrubution graph

fraud_counts = df['is_fraud'].value_counts()

plt.figure(figsize=(6,6))

plt.pie(
    fraud_counts,
    labels=['Normal', 'Fraud'],
    autopct='%1.1f%%'
)

plt.title('Fraud Distribution')

plt.show()

plt.figure(figsize=(10,6))

plt.hist(df['trust_score'], bins=40)

plt.xlabel('Trust Score')
plt.ylabel('Count')
plt.title('NGO Trust Score Distribution')

plt.show()

fraud = df[df['is_fraud'] == 1]
normal = df[df['is_fraud'] == 0]

plt.figure(figsize=(10,6))

plt.hist(
    normal['amount_difference'],
    bins=50,
    alpha=0.6,
    label='Normal'
)

plt.hist(
    fraud['amount_difference'],
    bins=50,
    alpha=0.6,
    label='Fraud'
)

plt.xlabel('Amount Difference')
plt.ylabel('Count')
plt.title('Amount Difference Distribution')
plt.legend()

plt.show()

fraud = df[df['is_fraud'] == 1]

plt.figure(figsize=(10,6))

plt.hist(fraud['submission_hour'], bins=24)

plt.xlabel('Hour of Day')
plt.ylabel('Fraud Count')
plt.title('Fraudulent Submission Timing')

plt.show()

plt.figure(figsize=(10,6))

plt.hist(
    normal['location_distance_km'],
    bins=40,
    alpha=0.6,
    label='Normal'
)

plt.hist(
    fraud['location_distance_km'],
    bins=40,
    alpha=0.6,
    label='Fraud'
)

plt.xlabel('Distance From Crisis Region (KM)')
plt.ylabel('Count')
plt.title('Geo Risk Distribution')
plt.legend()

plt.show()

numeric_df = df.select_dtypes(include=['int64', 'float64'])

corr = numeric_df.corr()

plt.figure(figsize=(12,10))

plt.imshow(corr)

plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
plt.yticks(range(len(corr.columns)), corr.columns)

plt.colorbar()

plt.title('Feature Correlation Matrix')

plt.show()

!pip install xgboost scikit-learn joblib

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from xgboost import XGBClassifier

import joblib

df = pd.read_csv("synthetic_ngo_fraud_dataset.csv")

print(df.head())

# =========================================================
# UPDATED STEP 4 — FEATURE ENGINEERING
# AidChain Fraud Detection Project
# =========================================================
# IMPORTANT:
# This version removes:
# - data leakage
# - overly deterministic features
# - unrealistic perfect fraud separability
#
# GOAL:
# Create realistic fraud intelligence signals
# =========================================================

import numpy as np

# =========================================================
# SAFETY CHECKS
# =========================================================

# Avoid division-by-zero errors
df["claimed_amount"] = df["claimed_amount"].replace(0, 1)

df["avg_claim_amount"] = df["avg_claim_amount"].replace(0, 1)

# =========================================================
# FEATURE 1 — Amount Difference
# Financial anomaly signal
# =========================================================

df["amount_difference"] = abs(
    df["claimed_amount"]
    - df["ocr_amount"]
)

# =========================================================
# FEATURE 2 — Amount Ratio
# Claimed vs OCR ratio
# =========================================================

df["amount_ratio"] = (
    df["claimed_amount"]
    / df["ocr_amount"]
)

# =========================================================
# FEATURE 3 — Amount Risk Score
# Normalized financial risk
# =========================================================

df["amount_risk_score"] = np.clip(

    df["amount_difference"]
    / df["claimed_amount"],

    0,
    1
)

# =========================================================
# FEATURE 4 — Trust Risk Score
# Lower trust = higher risk
# =========================================================

df["trust_risk_score"] = np.clip(

    (100 - df["trust_score"]) / 100,

    0,
    1
)

# =========================================================
# FEATURE 5 — Approval Risk Score
# Lower approval rate = suspicious NGO
# =========================================================

df["approval_risk_score"] = np.clip(

    1 - df["historical_approval_rate"],

    0,
    1
)

# =========================================================
# FEATURE 6 — Geo Risk Score
# Farther from crisis region = suspicious
# =========================================================

df["geo_risk_score"] = np.clip(

    df["location_distance_km"] / 100,

    0,
    1
)

# =========================================================
# FEATURE 7 — Frequency Risk Score
# Submission spam behavior
# =========================================================

df["frequency_risk_score"] = np.clip(

    df["submission_frequency"] / 20,

    0,
    1
)

# =========================================================
# FEATURE 8 — Claim Deviation Risk
# Compare current claim vs NGO historical average
# =========================================================

df["claim_deviation_risk"] = np.clip(

    abs(
        df["claimed_amount"]
        - df["avg_claim_amount"]
    )
    / df["avg_claim_amount"],

    0,
    5
)

# =========================================================
# FEATURE 9 — Night Activity Risk
# Fraud more likely during odd hours
# =========================================================

df["night_risk"] = df["submission_hour"].apply(

    lambda x: 1 if x <= 4 else 0
)

# =========================================================
# FEATURE 10 — High Frequency Flag
# Strong spam indicator
# =========================================================

df["high_frequency_flag"] = df[
    "submission_frequency"
].apply(

    lambda x: 1 if x > 12 else 0
)

# =========================================================
# FEATURE 11 — Large Claim Flag
# Detect unusually large reimbursements
# =========================================================

df["large_claim_flag"] = df[
    "claimed_amount"
].apply(

    lambda x: 1 if x > 10000 else 0
)

# =========================================================
# FEATURE 12 — Geo Outlier Flag
# Extreme distance anomaly
# =========================================================

df["geo_outlier_flag"] = df[
    "location_distance_km"
].apply(

    lambda x: 1 if x > 50 else 0
)

# =========================================================
# FEATURE 13 — Behavioral Risk Composite
# Multi-signal NGO risk behavior
# =========================================================

df["behavioral_risk_score"] = (

    (
        df["trust_risk_score"]
        + df["approval_risk_score"]
        + df["frequency_risk_score"]
    )

    / 3
)

# =========================================================
# FEATURE 14 — Financial Risk Composite
# Combined financial anomaly signal
# =========================================================

df["financial_risk_score"] = (

    (
        df["amount_risk_score"]
        + (df["claim_deviation_risk"] / 5)
    )

    / 2
)

# =========================================================
# FINAL FEATURE LIST
# =========================================================
# IMPORTANT:
# Removed:
# - risk_score
# - overly leaky deterministic columns
# =========================================================

FEATURE_COLUMNS = [

    # Financial
    "ocr_amount",
    "claimed_amount",
    "amount_difference",
    "amount_ratio",

    # NGO Behavior
    "trust_score",
    "historical_approval_rate",
    "submission_frequency",

    # Geo
    "location_distance_km",

    # Engineered Risk Scores
    "amount_risk_score",
    "trust_risk_score",
    "approval_risk_score",
    "geo_risk_score",
    "frequency_risk_score",
    "claim_deviation_risk",

    # Flags
    "night_risk",
    "high_frequency_flag",
    "large_claim_flag",
    "geo_outlier_flag",

    # Composite Features
    "behavioral_risk_score",
    "financial_risk_score"
]

# =========================================================
# TARGET VARIABLE
# =========================================================

TARGET = "is_fraud"

# =========================================================
# CLEANUP
# =========================================================

# Remove infinite values
df.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

# Remove missing values
df.dropna(inplace=True)

# =========================================================
# FINAL CHECK
# =========================================================

print("\n=================================================")
print("UPDATED FEATURE ENGINEERING COMPLETED")
print("=================================================\n")

print("Total Features:", len(FEATURE_COLUMNS))

print("\nFeature Columns:\n")

for feature in FEATURE_COLUMNS:
    print("-", feature)

print("\n=================================================")
print("FEATURE SAMPLE")
print("=================================================\n")

print(
    df[
        FEATURE_COLUMNS + [TARGET]
    ].head()
)

print("\n=================================================")
print("DATASET SHAPE AFTER CLEANING")
print("=================================================\n")

print(df.shape)

!pip install imbalanced-learn

from imblearn.over_sampling import SMOTE

# =========================================================
# TRAIN TEST SPLIT
# =========================================================

X = df[FEATURE_COLUMNS]

y = df[TARGET]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

# =========================================================
# APPLY SMOTE
# =========================================================

from imblearn.over_sampling import SMOTE

smote = SMOTE(
    random_state=42
)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(pd.Series(y_train_smote).value_counts())

from xgboost import XGBClassifier

model = XGBClassifier(

    n_estimators=300,

    max_depth=7,

    learning_rate=0.08,

    subsample=0.8,

    colsample_bytree=0.8,

    random_state=42,

    eval_metric="logloss"
)

model.fit(
    X_train_smote,
    y_train_smote
)

# =========================================================
# STEP 7 — MODEL PREDICTIONS
# =========================================================

y_pred = model.predict(X_test)

y_prob = model.predict_proba(X_test)[:,1]
print("Predictions Generated Successfully")

print("\nSample Predictions:")
print(y_pred[:10])

print("\nSample Fraud Probabilities:")
print(y_prob[:10])

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")

print(confusion_matrix(y_test, y_pred))

import joblib

joblib.dump(
    model,
    "aidchain_xgboost_model.pkl"
)

print("Model Saved")

# =========================================================
# AIDCHAIN FRAUD DETECTION API
# =========================================================

from fastapi import FastAPI
from pydantic import BaseModel

import pandas as pd
import numpy as np
import joblib

# =========================================================
# LOAD MODEL
# =========================================================

model = joblib.load(
    "aidchain_xgboost_model.pkl"
)

# =========================================================
# FASTAPI APP
# =========================================================

app = FastAPI(
    title="AidChain Fraud Detection API"
)

# =========================================================
# INPUT SCHEMA
# =========================================================

class FraudRequest(BaseModel):

    ocr_amount: float

    claimed_amount: float

    avg_claim_amount: float

    trust_score: float

    historical_approval_rate: float

    location_distance_km: float

    submission_frequency: int

    submission_hour: int

# =========================================================
# ROOT ROUTE
# =========================================================

@app.get("/")

def home():

    return {
        "message":
        "AidChain Fraud Detection API Running"
    }

# =========================================================
# PREDICTION ROUTE
# =========================================================

@app.post("/predict")

def predict(data: FraudRequest):

    # =====================================================
    # CONVERT INPUT TO DATAFRAME
    # =====================================================

    input_data = pd.DataFrame([{

        "ocr_amount":
            data.ocr_amount,

        "claimed_amount":
            data.claimed_amount,

        "amount_difference":
            abs(
                data.claimed_amount
                - data.ocr_amount
            ),

        "amount_ratio":
            data.claimed_amount
            / data.ocr_amount,

        "trust_score":
            data.trust_score,

        "historical_approval_rate":
            data.historical_approval_rate,

        "submission_frequency":
            data.submission_frequency,

        "location_distance_km":
            data.location_distance_km,

        # =================================================
        # ENGINEERED FEATURES
        # =================================================

        "amount_risk_score":

            abs(
                data.claimed_amount
                - data.ocr_amount
            )

            / data.claimed_amount,

        "trust_risk_score":

            (100 - data.trust_score)
            / 100,

        "approval_risk_score":

            1
            - data.historical_approval_rate,

        "geo_risk_score":

            data.location_distance_km
            / 100,

        "frequency_risk_score":

            data.submission_frequency
            / 20,

        "claim_deviation_risk":

            abs(
                data.claimed_amount
                - data.avg_claim_amount
            )

            / data.avg_claim_amount,

        "night_risk":

            1 if data.submission_hour <= 4
            else 0,

        "high_frequency_flag":

            1 if data.submission_frequency > 12
            else 0,

        "large_claim_flag":

            1 if data.claimed_amount > 10000
            else 0,

        "geo_outlier_flag":

            1 if data.location_distance_km > 50
            else 0,

        "behavioral_risk_score":

            (
                (
                    (100 - data.trust_score) / 100
                )

                +

                (
                    1
                    - data.historical_approval_rate
                )

                +

                (
                    data.submission_frequency
                    / 20
                )

            ) / 3,

        "financial_risk_score":

            (

                (
                    abs(
                        data.claimed_amount
                        - data.ocr_amount
                    )

                    / data.claimed_amount
                )

                +

                (
                    abs(
                        data.claimed_amount
                        - data.avg_claim_amount
                    )

                    / data.avg_claim_amount
                )

            ) / 2

    }])

    # =====================================================
    # MODEL PREDICTION
    # =====================================================

    fraud_probability = float(

        model.predict_proba(
            input_data
        )[0][1]

    )

    # =====================================================
    # RISK LOGIC
    # =====================================================

    if fraud_probability >= 0.75:

        risk_level = "HIGH"

        decision = "REJECT"

    elif fraud_probability >= 0.40:

        risk_level = "MEDIUM"

        decision = "MANUAL_REVIEW"

    else:

        risk_level = "LOW"

        decision = "APPROVE"

    # =====================================================
    # FINAL JSON RESPONSE
    # =====================================================

    return {

        "fraud_probability":
            round(fraud_probability, 4),

        "risk_level":
            risk_level,

        "decision":
            decision,

        "model_version":
            "v1.0.0"
    }

!pip install pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("3DMit6bowLpDX4xFbU1GuRkN0aP_WrE6pqhQ2bScchV4AVGN")

from pyngrok import ngrok
import threading
import uvicorn

# Start FastAPI server
def run():

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )

# Run in background
threading.Thread(
    target=run
).start()

# Create public tunnel
public_url = ngrok.connect(8000)

print("Public URL:", public_url)

from pyngrok import ngrok

ngrok.kill()